meta_product_name: "The Pool of Printables"
meta_title: "Pool of Printables - Get the High Quality 3D Designs you need when you need them."
meta_description: "The world's first crowdfunding platform for 3D designs. Get high quality ready-to-print 3D designs for a fraction of the original cost."
meta_image: "facebook-banner.jpg"
